DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS sub_course;
DROP TABLE IF EXISTS membership_price;
DROP TABLE IF EXISTS membership;
DROP TABLE IF EXISTS user_courses;
DROP TABLE IF EXISTS user_progress;
DROP TABLE IF EXISTS transactions;